server:
  port: 8009

spring:
  datasource:
    url: jdbc:sqlite:data/neorem.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      dialect: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:database/migrations

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /documentation

security:
  jwt:
    secret: replace_with_random_32_characters
    expiration: 8

scheduler:
  thread-pool: 5

dicom:
  local:
    aet: NEOREM
    port: 104
  remote:
    aet: MOCK_PACS
    host: localhost
    port: 105
  output:
    location: data/dicom
