CREATE TABLE studies (
    id                                BLOB     NOT NULL,
    patient_id                        BLOB     NULL,
    device_id                         BLOB     NULL,
    external_id                       TEXT     NULL,
    accession_id                      TEXT     NULL,
    modality                          TEXT     NULL,
    date                              TEXT     NULL,
    time                              TEXT     NULL,
    description                       TEXT     NULL,
    reason                            TEXT     NULL,
    procedure_requested               TEXT     NULL,
    procedure_performed               TEXT     NULL,
    institution                       TEXT     NULL,
    department                        TEXT     NULL,
    station                           TEXT     NULL,
    physicians                        TEXT     NULL,
    operators                         TEXT     NULL,
    height                            INTEGER  NULL,
    weight                            INTEGER  NULL,
    body_mass_index                   REAL     NULL,
    age                               INTEGER  NULL,
    pregnancy                         TEXT     NULL,
    comment                           TEXT     NULL,
    events_amount                     INTEGER  NULL,
    average_glandular_dose_left       REAL     NULL,
    average_glandular_dose_right      REAL     NULL,
    duration_total                    REAL     NULL,
    duration_fluoroscopy              REAL     NULL,
    duration_acquisition              REAL     NULL,
    dose_length_product               REAL     NULL,
    dose_area_product_total           REAL     NULL,
    dose_area_product_fluoroscopy     REAL     NULL,
    dose_area_product_acquisition     REAL     NULL,
    dose_reference_point_total        REAL     NULL,
    dose_reference_point_fluoroscopy  REAL     NULL,
    dose_reference_point_acquisition  REAL     NULL,
    pharmaceutical_agent              TEXT     NULL,
    pharmaceutical_radionuclide       TEXT     NULL,
    pharmaceutical_half_life          REAL     NULL,
    pharmaceutical_activity           REAL     NULL,
    pharmaceutical_dose               REAL     NULL,
    pharmaceutical_route              TEXT     NULL,
    pharmaceutical_laterality         TEXT     NULL,
    pharmaceutical_time               TEXT     NULL,
    pharmaceutical_comment            TEXT     NULL,

    PRIMARY KEY (id),
    UNIQUE (external_id)
);
