CREATE TABLE instances (
    id                        BLOB  NOT NUll,
    studies_id                BLOB  NOT NUll,
    series_id                 TEXT  NUll,
    event_id                  TEXT  NUll,
    modality                  TEXT  NUll,
    comment                   TEXT  NUll,
    date                      TEXT  NUll,
    time                      TEXT  NUll,
    protocol                  TEXT  NUll,
    type                      TEXT  NUll,
    plane                     TEXT  NUll,
    region                    TEXT  NUll,
    anatomy                   TEXT  NUll,
    laterality                TEXT  NUll,
    view                      TEXT  NUll,
    orientation               TEXT  NUll,
    exposure_time             REAL  NUll,
    exposure_time_rotation    REAL  NUll,
    duration                  REAL  NUll,
    scanning_length           REAL  NUll,
    pulse_width               REAL  NUll,
    pulse_rate                REAL  NUll,
    voltage_peak              REAL  NUll,
    tube_current              REAL  NUll,
    tube_current_peak         REAL  NUll,
    tube_current_time         REAL  NUll,
    dose_area_product         REAL  NUll,
    dose_length_product       REAL  NUll,
    dose_index_volume         REAL  NUll,
    dose_reference_point      REAL  NUll,
    dose_organ                REAL  NUll,
    modulation                TEXT  NUll,
    compression_thickness     REAL  NUll,
    exposure_index            REAL  NUll,
    exposure_index_target     REAL  NUll,
    exposure_index_deviation  REAL  NUll,

    PRIMARY KEY (id),
    FOREIGN KEY (studies_id) REFERENCES studies (id),
    UNIQUE (instance_id)
);
