CREATE TABLE events (
    id                        BLOB  NOT NUll,
    study_id                  BLOB  NOT NUll,
    external_id               TEXT  NUll,
    modality                  TEXT  NUll,
    comment                   TEXT  NUll,
    date                      TEXT  NUll,
    time                      TEXT  NUll,
    protocol                  TEXT  NUll,
    type                      TEXT  NUll,
    plane                     TEXT  NUll,
    region                    TEXT  NUll,
    anatomy                   TEXT  NUll,
    laterality                TEXT  NUll,
    view                      TEXT  NUll,
    orientation               TEXT  NUll,
    exposure_time             REAL  NUll,
    exposure_time_rotation    REAL  NUll,
    duration                  REAL  NUll,
    scanning_length           REAL  NUll,
    pulse_rate                REAL  NUll,
    pulse_time                REAL  NUll,
    voltage_peak              REAL  NUll,
    tube_current              REAL  NUll,
    tube_current_peak         REAL  NUll,
    tube_current_time         REAL  NUll,
    dose_area_product         REAL  NUll,
    dose_length_product       REAL  NUll,
    dose_index_volume         REAL  NUll,
    dose_reference_point      REAL  NUll,
    dose_organ                REAL  NUll,
    modulation                TEXT  NUll,
    compression_thickness     REAL  NUll,
    material_target           TEXT  NUll,
    material_filter           TEXT  NUll,

    PRIMARY KEY (id),
    UNIQUE (external_id)
);
